apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Chart.Name }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - services
  - endpoints
  - pods
  verbs:
  - get
  - list
  - watch
